# Generated by Django 3.2.3 on 2021-05-23 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=255)),
                ('technologies', models.CharField(max_length=255)),
                ('github', models.CharField(max_length=50)),
                ('image', models.CharField(blank=True, max_length=255, null=True)),
                ('alt', models.CharField(blank=True, max_length=30, null=True)),
                ('display', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
