# Generated by Django 3.2.3 on 2021-05-23 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='netlify',
            field=models.CharField(default='netlify', max_length=50),
            preserve_default=False,
        ),
    ]
