# Generated by Django 3.2.3 on 2021-05-23 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_netlify'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='alt',
            field=models.CharField(default='default', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.CharField(max_length=255),
        ),
    ]
