# Generated by Django 3.2.3 on 2021-05-23 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_project_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='netlify',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
