# Generated by Django 3.2.3 on 2021-05-23 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_alter_project_display'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='display',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='project',
            name='netlify',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
