# Generated by Django 3.2.3 on 2021-05-24 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_auto_20210523_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='netlify',
            field=models.CharField(default='', max_length=50),
        ),
    ]
