# Generated by Django 3.2.3 on 2021-05-30 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_auto_20210530_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='in',
            name='date',
            field=models.DateField(default='2021-01-01'),
            preserve_default=False,
        ),
    ]
